import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import styled from "styled-components";
const { motion } = require("framer-motion");
import Product from "../components/Products";
import Head from "next/head";
export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  const fade = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { ease: "easeOut", duration: 0.75, delay: 0.3 },
    },
  };

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oops!{error.message}</p>;
  const products = data.products.data;

  return (
    <>
      <Head>
        <title>Airshop | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>
      <main>
        <Heading>Our Products</Heading>
        <Gallery>
          {products &&
            products.map((product) => (
              <motion.div
                variants={fade}
                initial="hidden"
                key={product.attributes.slug}
                whileInView="visible"
              >
                <Product product={product} />
              </motion.div>
            ))}
        </Gallery>
      </main>
    </>
  );
}
const Gallery = styled(motion.div)`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(21rem, 1fr));
  grid-gap: 2rem;
  @media screen and (max-width: 402px) {
    grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));
  }
`;

const Hero = styled.div`
  background: url("../pexels-dominika-roseclay-2691961.jpg") center no-repeat;
  background-size: cover;
  width: 100vw;
  margin: 0 calc(-50vw + 50%);
  height: 83vh;
  margin-bottom: 2rem;
  overflow-x: visible;
`;

const Heading = styled.h2`
  text-align: center;
  padding-bottom: 2rem;
`;
